export const ENUMS = {
  CARD_TYPE: [
    ['攻击', 'thorn'],
    ['技能', 'bloom'],
    ['装备', 'root'],
    ['反制', 'guard'],
    ['任意', 'any'],
  ],
  QUALITY: [
    ['Common', 'Common'],
    ['Unusual', 'Unusual'],
    ['Epic', 'Epic'],
    ['Ultra', 'Ultra'],
    ['Super', 'Super'],
  ],
  TAG: [
    ['放逐', 'exile'],
    ['不可叠加', 'non_stackable'],
    ['精准', 'precision'],
    ['不可摧毁', 'indestructible'],
    ['萌芽', 'sprout'],
    ['共生', 'symbiosis'],
  ],
  STATUS: [
    ['中毒', 'poison'],
    ['灼烧', 'burn'],
    ['易伤', 'vulnus'],
    ['淬毒', 'toxic'],
    ['闪避', 'dodge'],
    ['无敌', 'invincible'],
    ['不可选中', 'untargetable'],
    ['装备保护', 'equip_protection'],
  ],
  ATTRIBUTE: [
    ['生命', 'health'],
    ['能量', 'energy'],
    ['魔力', 'magic'],
    ['护甲', 'armor'],
    ['能量上限', 'max_energy'],
    ['魔力上限', 'max_magic'],
    ['手牌数量', 'hand_size'],
    ['手牌上限', 'max_hand'],
  ],
  COMPARE: [
    ['=', '='],
    ['≠', '!='],
    ['<', '<'],
    ['>', '>'],
    ['≤', '<='],
    ['≥', '>='],
  ],
  MATH_OP: [
    ['+', '+'],
    ['-', '-'],
    ['×', '*'],
    ['÷', '/'],
    ['%', '%'],
    ['^', '^'],
    ['lg', 'log10'],
    ['ln', 'ln'],
    ['log₂', 'log2'],
    ['exp', 'exp'],
    ['1/x', 'reciprocal'],
    ['x²', 'square'],
    ['sin', 'sin'],
    ['cos', 'cos'],
    ['tan', 'tan'],
    ['asin', 'asin'],
    ['acos', 'acos'],
    ['atan', 'atan'],
    ['sinh', 'sinh'],
    ['cosh', 'cosh'],
    ['tanh', 'tanh'],
  ],
  ZONE: [
    ['手牌', 'hand'],
    ['抽牌堆', 'deck'],
    ['弃牌堆', 'discard'],
    ['放逐区', 'exile'],
  ],
  POSITION: [
    ['顶部', 'top'],
    ['底部', 'bottom'],
    ['随机', 'random'],
  ],
  TRIGGER_TIMING: [
    ['友方回合开始时', 'friendly_turn_start'],
    ['敌方回合开始时', 'enemy_turn_start'],
    ['友方行动阶段任意时刻', 'friendly_action_any'],
    ['敌方行动阶段任意时刻', 'enemy_action_any'],
    ['任意时刻', 'any_time'],
  ],
  RESPONSE_TIMING: [
    ['敌方使用攻击牌时', 'enemy_use_attack'],
    ['敌方使用技能牌时', 'enemy_use_skill'],
    ['敌方使用装备牌时', 'enemy_use_equipment'],
    ['敌方使用任意卡牌时', 'enemy_use_any'],
    ['友方装备即将被摧毁时', 'friendly_equip_destroy'],
    ['友方受到伤害时', 'friendly_take_damage'],
    ['友方即将受到致命伤害时', 'friendly_lethal_damage'],
  ],
  ROUND_MODE: [
    ['向上取整', 'ceil'],
    ['向下取整', 'floor'],
    ['四舍五入', 'round'],
  ],
  AND_OR: [
    ['且', 'and'],
    ['或', 'or'],
  ],
  BOOL_DROPDOWN: [
    ['是', 'true'],
    ['否', 'false'],
  ],
};

export const COLORS = {
  TRIGGER: 20,
  MANUAL_TRIGGER: 25,
  RESPONSE: 290,
  ACTION: 330,
  CONTROL: 120,
  CONDITION: 210,
  VALUE: 160,
  TARGET: 60,
  CARD_SELECTOR: 40,
  ENUM: 280,
};
