export const toolbox = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category',
      name: '事件触发器',
      colour: 20,
      contents: [
        { kind: 'block', type: 'trigger_on_play' },
        { kind: 'block', type: 'trigger_on_friendly_turn_start' },
        { kind: 'block', type: 'trigger_on_enemy_turn_start' },
        { kind: 'block', type: 'trigger_on_phys_damage' },
        { kind: 'block', type: 'trigger_on_any_damage' },
        { kind: 'block', type: 'trigger_on_lethal_damage' },
        { kind: 'block', type: 'trigger_on_draw_this' },
        { kind: 'block', type: 'trigger_on_end_turn_hand' },
        { kind: 'block', type: 'trigger_on_overflow_discard' },
        { kind: 'block', type: 'trigger_on_destroy' },
        { kind: 'block', type: 'trigger_on_durability_zero' },
        { kind: 'block', type: 'trigger_on_enemy_use_type' },
        { kind: 'block', type: 'trigger_on_friendly_use_type' },
        { kind: 'block', type: 'trigger_on_card_exile' },
        { kind: 'block', type: 'trigger_on_deck_empty' },
        { kind: 'block', type: 'trigger_on_self_magic_heal_cumulative' },
        { kind: 'block', type: 'trigger_on_self_damage' },
        { kind: 'block', type: 'trigger_on_event' },
      ],
    },
    {
      kind: 'category',
      name: '触发声明',
      colour: 25,
      contents: [
        { kind: 'block', type: 'trigger_manual' },
      ],
    },
    {
      kind: 'category',
      name: '响应声明',
      colour: 290,
      contents: [
        { kind: 'block', type: 'response_declare' },
      ],
    },
    {
      kind: 'category',
      name: '动作效果',
      colour: 330,
      contents: [
        {
          kind: 'category',
          name: '伤害与治疗',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_damage' },
            { kind: 'block', type: 'action_damage_multi' },
            { kind: 'block', type: 'action_heal' },
            { kind: 'block', type: 'action_set_health' },
            { kind: 'block', type: 'action_modify_damage' },
          ],
        },
        {
          kind: 'category',
          name: '状态效果',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_poison' },
            { kind: 'block', type: 'action_burn' },
            { kind: 'block', type: 'action_vulnus' },
            { kind: 'block', type: 'action_toxic' },
            { kind: 'block', type: 'action_add_armor' },
            { kind: 'block', type: 'action_remove_armor' },
            { kind: 'block', type: 'action_set_armor' },
            { kind: 'block', type: 'action_dodge_this' },
            { kind: 'block', type: 'action_dodge_permanent' },
            { kind: 'block', type: 'action_clear_buffs' },
            { kind: 'block', type: 'action_clear_debuffs' },
            { kind: 'block', type: 'action_clear_all_effects' },
            { kind: 'block', type: 'action_clear_status' },
          ],
        },
        {
          kind: 'category',
          name: '资源操作',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_gain_e' },
            { kind: 'block', type: 'action_gain_m' },
            { kind: 'block', type: 'action_cost_e' },
            { kind: 'block', type: 'action_cost_m' },
            { kind: 'block', type: 'action_mod_e_regen' },
            { kind: 'block', type: 'action_mod_m_regen' },
            { kind: 'block', type: 'action_mod_draw' },
          ],
        },
        {
          kind: 'category',
          name: '牌堆操作',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_draw' },
            { kind: 'block', type: 'action_discard' },
            { kind: 'block', type: 'action_choose_from_deck' },
            { kind: 'block', type: 'action_choose_from_discard' },
            { kind: 'block', type: 'action_choose_from_exile' },
            { kind: 'block', type: 'action_reveal_hand' },
            { kind: 'block', type: 'action_reveal_deck_top' },
            { kind: 'block', type: 'action_steal_card' },
            { kind: 'block', type: 'action_copy_card' },
            { kind: 'block', type: 'action_random_discard_from_hand' },
            { kind: 'block', type: 'action_put_card_to_deck' },
            { kind: 'block', type: 'action_shuffle_discard_into_deck' },
            { kind: 'block', type: 'action_give_card_to_hand' },
            { kind: 'block', type: 'action_give_card_to_deck' },
            { kind: 'block', type: 'action_give_card_to_discard' },
            { kind: 'block', type: 'action_remove_specific_card' },
          ],
        },
        {
          kind: 'category',
          name: '装备操作',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_destroy_random_equip' },
            { kind: 'block', type: 'action_destroy_all_equip' },
            { kind: 'block', type: 'action_destroy_all_field_equip' },
            { kind: 'block', type: 'action_equip_protection' },
            { kind: 'block', type: 'action_remove_equip_protection' },
            { kind: 'block', type: 'action_place_as_equip' },
          ],
        },
        {
          kind: 'category',
          name: '行动控制',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_block_action' },
            { kind: 'block', type: 'action_block_card_type' },
            { kind: 'block', type: 'action_force_card_type' },
            { kind: 'block', type: 'action_nullify_current_card' },
            { kind: 'block', type: 'action_invincible' },
            { kind: 'block', type: 'action_untargetable' },
            { kind: 'block', type: 'action_skip_turn' },
            { kind: 'block', type: 'action_extra_turn' },
            { kind: 'block', type: 'action_force_end_turn' },
            { kind: 'block', type: 'action_mark_self_damage_source' },
          ],
        },
        {
          kind: 'category',
          name: '卡牌修改',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_fission' },
            { kind: 'block', type: 'action_multiply_next_damage' },
            { kind: 'block', type: 'action_reduce_next_cost' },
            { kind: 'block', type: 'action_increase_next_cost' },
            { kind: 'block', type: 'action_fusion' },
            { kind: 'block', type: 'action_add_tag' },
            { kind: 'block', type: 'action_remove_tag' },
            { kind: 'block', type: 'action_transform_card' },
          ],
        },
        {
          kind: 'category',
          name: '耐久与计数',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_gain_durability' },
            { kind: 'block', type: 'action_lose_durability' },
            { kind: 'block', type: 'action_set_durability' },
            { kind: 'block', type: 'action_record_play_count' },
            { kind: 'block', type: 'action_record_equip_turns' },
            { kind: 'block', type: 'action_reset_counter' },
            { kind: 'block', type: 'action_create_counter' },
          ],
        },
        {
          kind: 'category',
          name: '特殊机制',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_exile_this' },
            { kind: 'block', type: 'action_move_to_discard' },
            { kind: 'block', type: 'action_move_to_deck' },
            { kind: 'block', type: 'action_global_damage_mult' },
            { kind: 'block', type: 'action_global_heal_mult' },
            { kind: 'block', type: 'action_global_cost_mult' },
            { kind: 'block', type: 'action_swap_health' },
            { kind: 'block', type: 'action_swap_hands' },
          ],
        },
        {
          kind: 'category',
          name: '自定义事件',
          colour: 330,
          contents: [
            { kind: 'block', type: 'action_broadcast_event' },
          ],
        },
      ],
    },
    {
      kind: 'category',
      name: '控制结构',
      colour: 120,
      contents: [
        { kind: 'block', type: 'control_if' },
        { kind: 'block', type: 'control_if_else' },
        { kind: 'block', type: 'control_repeat' },
        { kind: 'block', type: 'control_repeat_until' },
        { kind: 'block', type: 'control_for_each' },
        { kind: 'block', type: 'control_after_all' },
        { kind: 'block', type: 'control_random' },
      ],
    },
    {
      kind: 'category',
      name: '条件判断',
      colour: 210,
      contents: [
        { kind: 'block', type: 'condition_compare' },
        { kind: 'block', type: 'condition_equip_turns' },
        { kind: 'block', type: 'condition_durability' },
        { kind: 'block', type: 'condition_damage_value' },
        { kind: 'block', type: 'condition_target_attribute' },
        { kind: 'block', type: 'condition_has_tag' },
        { kind: 'block', type: 'condition_has_status' },
        { kind: 'block', type: 'condition_hand_has_type' },
        { kind: 'block', type: 'condition_has_equip' },
        { kind: 'block', type: 'condition_event_card_type' },
        { kind: 'block', type: 'condition_turn_number' },
        { kind: 'block', type: 'condition_and_or' },
        { kind: 'block', type: 'condition_not' },
        { kind: 'block', type: 'condition_hand_full' },
        { kind: 'block', type: 'condition_zone_contains' },
      ],
    },
    {
      kind: 'category',
      name: '数值来源',
      colour: 160,
      contents: [
        { kind: 'block', type: 'value_number' },
        { kind: 'block', type: 'value_target_attribute' },
        { kind: 'block', type: 'value_play_count' },
        { kind: 'block', type: 'value_equip_turns' },
        { kind: 'block', type: 'value_durability' },
        { kind: 'block', type: 'value_incoming_damage' },
        { kind: 'block', type: 'value_last_damage' },
        { kind: 'block', type: 'value_status_count' },
        { kind: 'block', type: 'value_hand_size' },
        { kind: 'block', type: 'value_discard_size' },
        { kind: 'block', type: 'value_equip_count' },
        { kind: 'block', type: 'value_exile_size' },
        { kind: 'block', type: 'value_deck_remaining' },
        { kind: 'block', type: 'value_turn_number' },
        { kind: 'block', type: 'value_random' },
        { kind: 'block', type: 'value_math_op' },
        { kind: 'block', type: 'value_round' },
        { kind: 'block', type: 'value_min_max' },
        { kind: 'block', type: 'value_clamp' },
      ],
    },
    {
      kind: 'category',
      name: '目标选择器',
      colour: 60,
      contents: [
        { kind: 'block', type: 'target_self' },
        { kind: 'block', type: 'target_enemy' },
        { kind: 'block', type: 'target_both' },
        { kind: 'block', type: 'target_random' },
        { kind: 'block', type: 'target_event_target' },
        { kind: 'block', type: 'target_event_source' },
        { kind: 'block', type: 'target_last_actor' },
        { kind: 'block', type: 'target_highest_health' },
        { kind: 'block', type: 'target_lowest_health' },
      ],
    },
    {
      kind: 'category',
      name: '卡牌选择器',
      colour: 40,
      contents: [
        { kind: 'block', type: 'card_selector_by_id' },
        { kind: 'block', type: 'card_selector_by_type' },
        { kind: 'block', type: 'card_selector_by_quality' },
        { kind: 'block', type: 'card_selector_by_tag' },
        { kind: 'block', type: 'card_selector_random' },
        { kind: 'block', type: 'card_selector_all' },
      ],
    },
  ],
};
